title: MyAnimeThoughts
author: Catherine Khuu, Vignesh Srinivasan
email: khuu9120@mylaurier.ca
description: > # this means to ignore newlines until "baseurl:"
  An anime and manga blog for weebs.
github_username:  khuu9120

sass:
    style: compressed

theme: Minima
